erDiagram
    ETUDIANT ||--o{ INSCRIPTION : "1,n s'inscrit 0,n"
    COURS ||--o{ INSCRIPTION : "1,n concerne 0,n"
    PROFESSEUR ||--o{ COURS : "1,1 enseigne 1,n"
    ETUDIANT ||--o{ NOTE : "1,n obtient 0,n"
    COURS ||--o{ NOTE : "1,n evalue 0,n"
    DEPARTEMENT ||--o{ PROFESSEUR : "1,1 emploie 0,n"
    DEPARTEMENT ||--o{ COURS : "1,1 propose 0,n"
    PERSONNEL_ADMIN ||--o{ PLANNING : "1,1 gere 0,n"
    COURS ||--o{ PLANNING : "1,1 planifie 0,n"
    SALLE ||--o{ PLANNING : "1,1 occupe 0,n"
    
    ETUDIANT {
        _ numero_etudiant
        _ nom
        _ prenom
        _ date_naissance
        _ email
        _ telephone
        _ adresse
    }
    PROFESSEUR {
        _ numero_professeur
        _ nom
        _ prenom
        _ email
        _ specialite
        _ date_embauche
    }
    COURS {
        _ code_cours
        _ nom_cours
        _ description
        _ credits
        _ heures
    }
    DEPARTEMENT {
        _ code_departement
        _ nom_departement
        _ batiment
    }
    PERSONNEL_ADMIN {
        _ numero_admin
        _ nom
        _ prenom
        _ email
        _ poste
        _ date_embauche
    }
    SALLE {
        _ numero_salle
        _ batiment
        _ capacite
        _ type_salle
    }
    INSCRIPTION {
        _ date_inscription
        _ statut
        _ semestre
    }
    NOTE {
        _ note
        _ date_examen
        _ type_evaluation
    }
    PLANNING {
        _ date_cours
        _ heure_debut
        _ heure_fin
        _ jour_semaine
    }
