erDiagram
    DEPARTEMENT ||--o{ PROFESSEUR : ""
    DEPARTEMENT ||--o{ COURS : ""
    PROFESSEUR ||--o{ COURS : ""
    ETUDIANT ||--o{ INSCRIPTION : ""
    COURS ||--o{ INSCRIPTION : ""
    ETUDIANT ||--o{ NOTE : ""
    COURS ||--o{ NOTE : ""
    PERSONNEL_ADMIN ||--o{ PLANNING : ""
    COURS ||--o{ PLANNING : ""
    SALLE ||--o{ PLANNING : ""
    
    ETUDIANT {
        _ id_etudiant PK
        _ numero_etudiant
        _ nom
        _ prenom
        _ date_naissance
        _ email
        _ telephone
        _ adresse
        _ date_inscription
    }
    PROFESSEUR {
        _ id_professeur PK
        _ id_departement FK
        _ numero_professeur
        _ nom
        _ prenom
        _ email
        _ specialite
        _ date_embauche
    }
    COURS {
        _ id_cours PK
        _ id_professeur FK
        _ id_departement FK
        _ code_cours
        _ nom_cours
        _ description
        _ credits
        _ heures
    }
    DEPARTEMENT {
        _ id_departement PK
        _ code_departement
        _ nom_departement
        _ batiment
    }
    PERSONNEL_ADMIN {
        _ id_admin PK
        _ numero_admin
        _ nom
        _ prenom
        _ email
        _ poste
        _ date_embauche
    }
    SALLE {
        _ id_salle PK
        _ numero_salle
        _ batiment
        _ capacite
        _ type_salle
    }
    INSCRIPTION {
        _ id_inscription PK
        _ id_etudiant FK
        _ id_cours FK
        _ date_inscription
        _ statut
        _ semestre
    }
    NOTE {
        _ id_note PK
        _ id_etudiant FK
        _ id_cours FK
        _ note
        _ date_examen
        _ type_evaluation
    }
    PLANNING {
        _ id_planning PK
        _ id_admin FK
        _ id_cours FK
        _ id_salle FK
        _ date_cours
        _ heure_debut
        _ heure_fin
        _ jour_semaine
    }
